# Generated by Django 5.2.4 on 2025-07-25 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='The content of the notification.', max_length=255, verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('connection_request', 'Connection Request'), ('connection_approved', 'Connection Approved'), ('connection_denied', 'Connection Denied'), ('connection_terminated', 'Connection Terminated'), ('reminder', 'Reminder'), ('appointment_request', 'Appointment Request'), ('appointment_approved', 'Appointment Approved'), ('appointment_rejected', 'Appointment Rejected'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_reminder', 'Appointment Reminder')], default='reminder', help_text='Type/category of the notification (e.g., reminder, info, etc).', max_length=30, verbose_name='Notification Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the notification was created.', verbose_name='Created At')),
                ('is_read', models.BooleanField(default=False, help_text='Indicates whether the notification has been read.', verbose_name='Is Read')),
                ('recipient', models.ForeignKey(help_text='User (doctor or patient) who will receive the notification.', limit_choices_to={'role__in': ['doctor', 'patient']}, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient'], name='notificatio_recipie_be3f1a_idx'), models.Index(fields=['is_read'], name='notificatio_is_read_9edb86_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
