version: '3.8'

services:
  db:
    image: postgres:15
    container_name: healthdataway_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    container_name: healthdataway_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
