version: '3.8'

services:
  db:
    image: postgres:15
    container_name: healthdataway_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: redis:7
    container_name: healthdataway_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthdataway_web
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./staticfiles:/code/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - backend

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthdataway_celery
    command: celery -A config worker --loglevel=info --pool=solo
    environment:
      - PYTHONPATH=/code/src
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - backend


volumes:
  postgres_data:

networks:
  backend:
