version: '3.8'

services:
  db:
    image: postgres:15
    container_name: healthdataway_postgres
    restart: always
    env_file:
      - ./src/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: redis:7
    container_name: healthdataway_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthdataway_web
    command: /code/entrypoint.sh
    volumes:
      - .:/code
    env_file:
      - ./src/.env
    environment:
      - PYTHONPATH=/code/src
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    networks:
      - backend

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthdataway_celery
    command: celery -A config worker --loglevel=info --pool=solo
    environment:
      - PYTHONPATH=/code/src
    volumes:
      - .:/code
    env_file:
      - ./src/.env
    depends_on:
      - db
      - redis
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: healthdataway_nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./staticfiles:/vol/web/static
      - ./media:/vol/web/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
