# Directions
DIRECTION_CARDIOLOGY = 'cardiology'
DIRECTION_ENDOCRINOLOGY = 'endocrinology'

DIRECTION_CHOICES = [
    (DIRECTION_CARDIOLOGY, 'Cardiology'),
    (DIRECTION_ENDOCRINOLOGY, 'Endocrinology'),
]

DIRECTION_VALUES = {DIRECTION_CARDIOLOGY, DIRECTION_ENDOCRINOLOGY}

# Statuses
STATUS_PENDING = 'pending'
STATUS_APPROVED = 'approved'
STATUS_DECLINED = 'declined'
STATUS_CANCELLED_BY_DOCTOR = 'cancelled_by_doctor'
STATUS_CANCELLED_BY_PATIENT = 'cancelled_by_patient'

STATUS_CHOICES = [
    (STATUS_PENDING, 'Pending'),
    (STATUS_APPROVED, 'Approved'),
    (STATUS_DECLINED, 'Declined'),
    (STATUS_CANCELLED_BY_DOCTOR, 'Cancelled by Doctor'),
    (STATUS_CANCELLED_BY_PATIENT, 'Cancelled by Patient'),
]

STATUS_VALUES = {
    STATUS_PENDING,
    STATUS_APPROVED,
    STATUS_DECLINED,
    STATUS_CANCELLED_BY_DOCTOR,
    STATUS_CANCELLED_BY_PATIENT,
}
