# Generated by Django 5.2.4 on 2025-08-02 20:47

import connections.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPatientLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('cardiology', 'Cardiology'), ('endocrinology', 'Endocrinology')], help_text='Medical specialty for this doctor-patient link.', max_length=20, validators=[connections.validators.validate_direction], verbose_name='Medical Direction')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled_by_doctor', 'Cancelled by Doctor'), ('cancelled_by_patient', 'Cancelled by Patient')], default='pending', help_text='Current status of the connection.', max_length=30, validators=[connections.validators.validate_status], verbose_name='Connection Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the connection was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when the connection was last updated.', verbose_name='Updated At')),
                ('doctor', models.ForeignKey(help_text='The doctor in this doctor-patient connection.', limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_links', to=settings.AUTH_USER_MODEL, verbose_name='Doctor')),
                ('patient', models.ForeignKey(help_text='The patient in this doctor-patient connection.', limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_links', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Doctor-Patient Link',
                'verbose_name_plural': 'Doctor-Patient Links',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'patient', 'direction'), name='unique_doctor_patient_direction')],
            },
        ),
    ]
