# Generated by Django 5.2.4 on 2025-08-02 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_datetime', models.DateTimeField(help_text='The scheduled date and time of the appointment.', verbose_name='Appointment Date & Time')),
                ('reason', models.CharField(blank=True, help_text='Optional reason or note for the appointment.', max_length=255, verbose_name='Reason for Visit')),
                ('is_confirmed', models.BooleanField(default=False, help_text='Indicates whether the appointment has been approved by the doctor.', verbose_name='Confirmed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the appointment was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('doctor', models.ForeignKey(help_text='The doctor for this appointment.', limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_doctor', to=settings.AUTH_USER_MODEL, verbose_name='Doctor')),
                ('patient', models.ForeignKey(help_text='The patient for this appointment.', limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_patient', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['appointment_datetime'],
                'indexes': [models.Index(fields=['doctor'], name='appointment_doctor__649ad1_idx'), models.Index(fields=['patient'], name='appointment_patient_94a7ef_idx'), models.Index(fields=['appointment_datetime'], name='appointment_appoint_ff6788_idx')],
            },
        ),
    ]
