name: Build and deploy Django app to Azure Web App - healthdataway

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run collectstatic
        run: |
          python src/manage.py collectstatic --noinput
        env:
          DJANGO_SETTINGS_MODULE: config.settings

      - name: Test DNS resolution
        run: |
          echo "🔍 Testing DNS for PostgreSQL host"
          ping -c 3 healthdataway-server.postgres.database.azure.com || true

      - name: Run migrations (with debug info)
        run: |
          python src/manage.py migrate
        env:
          DJANGO_SETTINGS_MODULE: config.settings

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'healthdataway'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
